import React,{useEffect,useState}from'react';
const key='rekon_token';
async function api(p,o={}){const h={Accept:'application/json',...(o.headers||{})};if(o.body&&typeof o.body!=='string'&&!(o.body instanceof FormData)){h['Content-Type']='application/json';o={...o,body:JSON.stringify(o.body)}}const t=localStorage.getItem(key);if(t)h.Authorization=`Bearer ${t}`;const r=await fetch('/api'+p,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok){const e=Object.values(d.errors||{}).flat().join(' ');throw Error(e||d.message||'Permintaan gagal.')}return d}
export function AdminManagement({onMessage,user}){const[t,setT]=useState('Tahun Anggaran');const tabs=['Tahun Anggaran','SKPD','Pejabat','Pengguna'];if(user?.role==='admin')tabs.push('Import Master');return <section><div className="tabs">{tabs.map(x=><button key={x} className={t===x?'tab-active':''} onClick={()=>setT(x)}>{x}</button>)}</div>{t==='Tahun Anggaran'?<Years onMessage={onMessage}/>:t==='SKPD'?<Skpds onMessage={onMessage}/>:t==='Pejabat'?<Officials onMessage={onMessage}/>:t==='Pengguna'?<Users onMessage={onMessage}/>:<MasterImport onMessage={onMessage}/>}</section>}
function Years({onMessage}){const[a,setA]=useState([]),[y,setY]=useState(new Date().getFullYear());const load=()=>api('/years').then(setA);useEffect(()=>{load().catch(e=>onMessage(e.message))},[]);return <div className="admin-grid"><section className="panel"><h2>Tambah tahun</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await api('/years',{method:'POST',body:{year:Number(y)}});onMessage('Tahun ditambahkan.');load()}catch(e){onMessage(e.message)}}}><label>Tahun<input type="number" value={y} onChange={e=>setY(e.target.value)} required/></label><button className="primary">Tambah</button></form></section><section className="panel"><h2>Daftar tahun</h2><div className="table-wrap"><table><thead><tr><th>Tahun</th><th>Status</th><th/></tr></thead><tbody>{a.map(x=><tr key={x.id}><td>{x.year}</td><td>{x.is_active?'Aktif':'Tidak aktif'}</td><td>{!x.is_active&&<button className="link-button" onClick={async()=>{try{await api(`/years/${x.id}/activate`,{method:'POST'});load()}catch(e){onMessage(e.message)}}}>Aktifkan</button>}</td></tr>)}</tbody></table></div></section></div>}
function Skpds({onMessage}){return <Crud title="SKPD" endpoint="/skpds" fields={['code','name']} onMessage={onMessage}/>}
function Officials({onMessage}){return <Crud title="Pejabat" endpoint="/officials" fields={['name','nip','position','skpd_id']} onMessage={onMessage}/>}
function Users({onMessage}){return <Crud title="Pengguna" endpoint="/users" fields={['name','email','password','role','skpd_id']} onMessage={onMessage}/>}
function MasterImport({onMessage}){const[file,setFile]=useState(null),[year,setYear]=useState(new Date().getFullYear()),[busy,setBusy]=useState(false),[result,setResult]=useState(null);async function submit(e){e.preventDefault();if(!file)return;setBusy(true);setResult(null);try{const body=new FormData();body.append('file',file);body.append('source_year',String(year));const d=await api('/master-data/import',{method:'POST',body});setResult(d);onMessage(d.message)}catch(e){onMessage(e.message)}finally{setBusy(false)}}return <div className="admin-grid"><section className="panel"><h2>Import master data</h2><p>Gunakan file Excel dengan sheet data utama dan kolom: <strong>kode, uraian, jenis, level, parent</strong>.</p><form className="form-stack" onSubmit={submit}><label>Tahun<input type="number" value={year} onChange={e=>setYear(e.target.value)} min="2000" max="2100" required/></label><label>File Excel<input type="file" accept=".xlsx,.xls" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><button className="primary" disabled={busy||!file}>{busy?'Mengimpor…':'Import master'}</button></form></section>{result&&<section className="panel"><h2>Hasil import</h2><p>{result.rows} baris master diproses.</p><p>{result.skpds} data SKPD disinkronkan.</p><p>Tahun: {result.year??'—'}</p><p>Import bersifat upsert per tahun: data pada tahun yang sama diperbarui, sedangkan kode yang sama pada tahun berbeda tetap menjadi record terpisah.</p></section>}</div>}
function Crud({title,endpoint,fields,onMessage}){const[a,setA]=useState([]),[f,setF]=useState({});const load=()=>api(endpoint).then(d=>setA(d.data||d));useEffect(()=>{load().catch(e=>onMessage(e.message))},[]);async function save(e){e.preventDefault();try{await api(endpoint,{method:'POST',body:f});onMessage(`${title} dibuat.`);setF({});load()}catch(e){onMessage(e.message)}}return <div className="admin-grid"><section className="panel"><h2>{title} baru</h2><form className="form-stack" onSubmit={save}>{fields.map(x=><label key={x}>{x}<input type={x==='password'?'password':'text'} value={f[x]||''} onChange={e=>setF({...f,[x]:e.target.value})} required={x!=='nip'&&x!=='password'}/></label>)}<button className="primary">Simpan</button></form></section><section className="panel"><h2>Daftar {title}</h2><div className="table-wrap"><table><tbody>{a.map(x=><tr key={x.id}><td><strong>{x.name||x.code}</strong><span>{x.email||x.position||''}</span></td></tr>)}</tbody></table></div></section></div>}
