import React,{useEffect,useState}from'react';
const key='rekon_token';
async function api(p,o={}){const h={Accept:'application/json',...(o.headers||{})};if(o.body&&typeof o.body!=='string'){h['Content-Type']='application/json';o={...o,body:JSON.stringify(o.body)}}const t=localStorage.getItem(key);if(t)h.Authorization=`Bearer ${t}`;const r=await fetch('/api'+p,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Permintaan gagal.');return d}
export function AdminManagement({onMessage}){const[t,setT]=useState('Tahun Anggaran');return <section><div className="tabs">{['Tahun Anggaran','SKPD','Pejabat','Pengguna'].map(x=><button key={x} className={t===x?'tab-active':''} onClick={()=>setT(x)}>{x}</button>)}</div>{t==='Tahun Anggaran'?<Years onMessage={onMessage}/>:t==='SKPD'?<Skpds onMessage={onMessage}/>:t==='Pejabat'?<Officials onMessage={onMessage}/>:<Users onMessage={onMessage}/>}</section>}
function Years({onMessage}){const[a,setA]=useState([]),[y,setY]=useState(new Date().getFullYear());const load=()=>api('/years').then(setA);useEffect(()=>{load().catch(e=>onMessage(e.message))},[]);return <div className="admin-grid"><section className="panel"><h2>Tambah tahun</h2><form className="form-stack" onSubmit={async e=>{e.preventDefault();try{await api('/years',{method:'POST',body:{year:Number(y)}});onMessage('Tahun ditambahkan.');load()}catch(e){onMessage(e.message)}}}><label>Tahun<input type="number" value={y} onChange={e=>setY(e.target.value)} required/></label><button className="primary">Tambah</button></form></section><section className="panel"><h2>Daftar tahun</h2><div className="table-wrap"><table><thead><tr><th>Tahun</th><th>Status</th><th/></tr></thead><tbody>{a.map(x=><tr key={x.id}><td>{x.year}</td><td>{x.is_active?'Aktif':'Tidak aktif'}</td><td>{!x.is_active&&<button className="link-button" onClick={async()=>{try{await api(`/years/${x.id}/activate`,{method:'POST'});load()}catch(e){onMessage(e.message)}}}>Aktifkan</button>}</td></tr>)}</tbody></table></div></section></div>}
function Skpds({onMessage}){return <Crud title="SKPD" endpoint="/skpds" fields={['code','name']} onMessage={onMessage}/>}
function Officials({onMessage}){return <Crud title="Pejabat" endpoint="/officials" fields={['name','nip','position','skpd_id']} onMessage={onMessage}/>}
function Users({onMessage}){return <Crud title="Pengguna" endpoint="/users" fields={['name','email','password','role','skpd_id']} onMessage={onMessage}/>}
function Crud({title,endpoint,fields,onMessage}){const[a,setA]=useState([]),[f,setF]=useState({});const load=()=>api(endpoint).then(d=>setA(d.data||d));useEffect(()=>{load().catch(e=>onMessage(e.message))},[]);async function save(e){e.preventDefault();try{await api(endpoint,{method:'POST',body:f});onMessage(`${title} dibuat.`);setF({});load()}catch(e){onMessage(e.message)}}return <div className="admin-grid"><section className="panel"><h2>{title} baru</h2><form className="form-stack" onSubmit={save}>{fields.map(x=><label key={x}>{x}<input type={x==='password'?'password':'text'} value={f[x]||''} onChange={e=>setF({...f,[x]:e.target.value})} required={x!=='nip'&&x!=='password'}/></label>)}<button className="primary">Simpan</button></form></section><section className="panel"><h2>Daftar {title}</h2><div className="table-wrap"><table><tbody>{a.map(x=><tr key={x.id}><td><strong>{x.name||x.code}</strong><span>{x.email||x.position||''}</span></td></tr>)}</tbody></table></div></section></div>}
